/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as AuthUserRouteImport } from './routes/_auth/_user'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthUserIndexRouteImport } from './routes/_auth/_user/index'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUserRoute = AuthUserRouteImport.update({
  id: '/_user',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthUserIndexRoute = AuthUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthUserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthUserIndexRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/setup/': typeof SetupIndexRoute
  '/admin/': typeof AuthAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthUserIndexRoute
  '/login': typeof GuestLoginRoute
  '/setup': typeof SetupIndexRoute
  '/admin': typeof AuthAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_auth/_user': typeof AuthUserRouteWithChildren
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/setup/': typeof SetupIndexRoute
  '/_auth/_user/': typeof AuthUserIndexRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/login' | '/setup/' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/setup' | '/admin'
  id:
    | '__root__'
    | '/_auth'
    | '/_guest'
    | '/_auth/_user'
    | '/_auth/admin'
    | '/_guest/login'
    | '/setup/'
    | '/_auth/_user/'
    | '/_auth/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  SetupIndexRoute: typeof SetupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_user': {
      id: '/_auth/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthUserRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/_user/': {
      id: '/_auth/_user/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthUserIndexRouteImport
      parentRoute: typeof AuthUserRoute
    }
  }
}

interface AuthUserRouteChildren {
  AuthUserIndexRoute: typeof AuthUserIndexRoute
}

const AuthUserRouteChildren: AuthUserRouteChildren = {
  AuthUserIndexRoute: AuthUserIndexRoute,
}

const AuthUserRouteWithChildren = AuthUserRoute._addFileChildren(
  AuthUserRouteChildren,
)

interface AuthAdminRouteChildren {
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthRouteChildren {
  AuthUserRoute: typeof AuthUserRouteWithChildren
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthUserRoute: AuthUserRouteWithChildren,
  AuthAdminRoute: AuthAdminRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  SetupIndexRoute: SetupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
